# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VolleyBallBoxScore' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for VolleyBallBoxScore

pod 'SVProgressHUD', '~> 2.1.2'
  target 'VolleyBallBoxScoreTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'VolleyBallBoxScoreUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
